[project]
name = "extension-ai-obsidian"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "colorama>=0.4.6",
    "openai>=1.77.0",
    "python-dotenv>=1.1.0",
]
